Write-Host "=== Vercel Full Deploy Setup ===" -ForegroundColor Cyan

function Write-B64 { param($p,$b)
  $full = Join-Path (Get-Location).Path $p
  $dir = Split-Path $full -Parent
  if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  $bytes = [Convert]::FromBase64String($b)
  $text = [System.Text.Encoding]::UTF8.GetString($bytes)
  [System.IO.File]::WriteAllText($full, $text, (New-Object System.Text.UTF8Encoding $false))
  Write-Host "  -> $p" -ForegroundColor Gray
}

Write-B64 "vercel.json" "ewogICJ2ZXJzaW9uIjogMiwKICAiYnVpbGRzIjogWwogICAgewogICAgICAic3JjIjogImZyb250ZW5kL3BhY2thZ2UuanNvbiIsCiAgICAgICJ1c2UiOiAiQHZlcmNlbC9zdGF0aWMtYnVpbGQiLAogICAgICAiY29uZmlnIjogeyAiZGlzdERpciI6ICJkaXN0IiB9CiAgICB9LAogICAgewogICAgICAic3JjIjogImFwaS9pbmRleC5weSIsCiAgICAgICJ1c2UiOiAiQHZlcmNlbC9weXRob24iCiAgICB9CiAgXSwKICAicm91dGVzIjogWwogICAgeyAic3JjIjogIi9hcGkvKC4qKSIsICJkZXN0IjogIi9hcGkvaW5kZXgucHkiIH0sCiAgICB7ICJzcmMiOiAiL2F1dGgvKC4qKSIsICJkZXN0IjogIi9hcGkvaW5kZXgucHkiIH0sCiAgICB7ICJzcmMiOiAiL2J1ZGdldC8oLiopIiwgImRlc3QiOiAiL2FwaS9pbmRleC5weSIgfSwKICAgIHsgInNyYyI6ICIvYXVkaXQvKC4qKSIsICJkZXN0IjogIi9hcGkvaW5kZXgucHkiIH0sCiAgICB7ICJzcmMiOiAiL3Byb2N1cmVtZW50LyguKikiLCAiZGVzdCI6ICIvYXBpL2luZGV4LnB5IiB9LAogICAgeyAic3JjIjogIi9yZXZlbnVlLyguKikiLCAiZGVzdCI6ICIvYXBpL2luZGV4LnB5IiB9LAogICAgeyAic3JjIjogIi9hZG1pbi8oLiopIiwgImRlc3QiOiAiL2FwaS9pbmRleC5weSIgfSwKICAgIHsgInNyYyI6ICIvYWkvKC4qKSIsICJkZXN0IjogIi9hcGkvaW5kZXgucHkiIH0sCiAgICB7ICJzcmMiOiAiL2V4cG9ydHMvKC4qKSIsICJkZXN0IjogIi9hcGkvaW5kZXgucHkiIH0sCiAgICB7ICJzcmMiOiAiL2twaS8oLiopIiwgImRlc3QiOiAiL2FwaS9pbmRleC5weSIgfSwKICAgIHsgInNyYyI6ICIvcHJlbWl1bS8oLiopIiwgImRlc3QiOiAiL2FwaS9pbmRleC5weSIgfSwKICAgIHsgInNyYyI6ICIvaGVhbHRoIiwgImRlc3QiOiAiL2FwaS9pbmRleC5weSIgfSwKICAgIHsgInNyYyI6ICIvb3BlbmFwaS5qc29uIiwgImRlc3QiOiAiL2FwaS9pbmRleC5weSIgfSwKICAgIHsgInNyYyI6ICIvZG9jcyIsICJkZXN0IjogIi9hcGkvaW5kZXgucHkiIH0sCiAgICB7ICJzcmMiOiAiLyguKikiLCAiZGVzdCI6ICIvZnJvbnRlbmQvJDEiIH0KICBdLAogICJlbnYiOiB7CiAgICAiREFUQUJBU0VfVVJMIjogIkBkYXRhYmFzZV91cmwiLAogICAgIkpXVF9TRUNSRVQiOiAiQGp3dF9zZWNyZXQiLAogICAgIkNPUlNfT1JJR0lOUyI6ICJodHRwczovL2J1ZGdldG5ldy52ZXJjZWwuYXBwIgogIH0KfQo="
Write-B64 "api\index.py" "aW1wb3J0IHN5cwppbXBvcnQgb3MKc3lzLnBhdGguaW5zZXJ0KDAsIG9zLnBhdGguam9pbihvcy5wYXRoLmRpcm5hbWUoX19maWxlX18pLCAiLi4iKSkKZnJvbSBiYWNrZW5kLmFwcC5tYWluIGltcG9ydCBhcHAK"
Write-B64 "requirements.txt" "ZmFzdGFwaT49MC4xMTUKdXZpY29ybltzdGFuZGFyZF0+PTAuMzAKcHlkYW50aWM+PTIuNwpweWRhbnRpYy1zZXR0aW5ncz49Mi40CnNxbGFsY2hlbXk+PTIuMAphbGVtYmljPj0xLjEzCnBzeWNvcGdbYmluYXJ5XT49My4yCnB5dGhvbi1qb3NlW2NyeXB0b2dyYXBoeV0+PTMuMwpwYXNzbGliPj0xLjcKcHl0aG9uLW11bHRpcGFydD49MC4wLjkKb3Jqc29uPj0zLjEwCmh0dHB4Pj0wLjI3Cm9wZW5weXhsPj0zLjEKcmVwb3J0bGFiPj00LjIKcHlvdHA+PTIuOQpzbG93YXBpPj0wLjEuOQo="
Write-B64 "backend\app\settings.py" "ZnJvbSBweWRhbnRpY19zZXR0aW5ncyBpbXBvcnQgQmFzZVNldHRpbmdzLCBTZXR0aW5nc0NvbmZpZ0RpY3QKCgpjbGFzcyBTZXR0aW5ncyhCYXNlU2V0dGluZ3MpOgogICAgbW9kZWxfY29uZmlnID0gU2V0dGluZ3NDb25maWdEaWN0KGVudl9maWxlPSIuZW52IiwgZXh0cmE9Imlnbm9yZSIpCgogICAgYXBwX2Vudjogc3RyID0gInByb2R1Y3Rpb24iCiAgICBkYXRhYmFzZV91cmw6IHN0ciA9ICJzcWxpdGU6Ly8vLi9idWRnZXRuZXcuZGIiCgogICAgand0X3NlY3JldDogc3RyID0gImJ1ZGdldG5ldy1jaGFuZ2UtaW4tcHJvZHVjdGlvbi0yMDI2IgogICAgand0X2lzc3Vlcjogc3RyID0gImJ1ZGdldG5ldyIKICAgIGNvcnNfb3JpZ2luczogc3RyID0gImh0dHBzOi8vYnVkZ2V0bmV3LnZlcmNlbC5hcHAsaHR0cDovL2xvY2FsaG9zdDo1MTczIgoKCnNldHRpbmdzID0gU2V0dGluZ3MoKQo="
Write-B64 "backend\app\db.py" "ZnJvbSBzcWxhbGNoZW15IGltcG9ydCBjcmVhdGVfZW5naW5lCmZyb20gc3FsYWxjaGVteS5vcm0gaW1wb3J0IERlY2xhcmF0aXZlQmFzZSwgc2Vzc2lvbm1ha2VyCgpmcm9tIGFwcC5zZXR0aW5ncyBpbXBvcnQgc2V0dGluZ3MKCgpjbGFzcyBCYXNlKERlY2xhcmF0aXZlQmFzZSk6CiAgICBwYXNzCgoKIyBTUUxpdGUgbmVlZHMgY29ubmVjdF9hcmdzLCBQb3N0Z3JlU1FMIGRvZXMgbm90CmNvbm5lY3RfYXJncyA9IHsiY2hlY2tfc2FtZV90aHJlYWQiOiBGYWxzZX0gaWYgc2V0dGluZ3MuZGF0YWJhc2VfdXJsLnN0YXJ0c3dpdGgoInNxbGl0ZSIpIGVsc2Uge30KZW5naW5lID0gY3JlYXRlX2VuZ2luZShzZXR0aW5ncy5kYXRhYmFzZV91cmwsIHBvb2xfcHJlX3Bpbmc9VHJ1ZSwgY29ubmVjdF9hcmdzPWNvbm5lY3RfYXJncykKU2Vzc2lvbkxvY2FsID0gc2Vzc2lvbm1ha2VyKGJpbmQ9ZW5naW5lLCBhdXRvZmx1c2g9RmFsc2UsIGF1dG9jb21taXQ9RmFsc2UpCgoKZGVmIGluaXRfZGIoKSAtPiBOb25lOgogICAgZnJvbSBhcHAgaW1wb3J0IG1vZGVscyAgIyBub3FhOiBGNDAxCiAgICBmcm9tIGFwcCBpbXBvcnQgbW9kZWxzX3ByZW1pdW0gICMgbm9xYTogRjQwMQogICAgQmFzZS5tZXRhZGF0YS5jcmVhdGVfYWxsKGJpbmQ9ZW5naW5lKQo="
Write-B64 "frontend\.env.production" "VklURV9BUElfQkFTRV9VUkw9"

Write-Host "Commit & push..." -ForegroundColor Yellow
git add -A
$c = git commit -m "feat: full Vercel deployment — api/index.py + vercel.json + SQLite fallback" 2>&1
Write-Host "  $c" -ForegroundColor Gray
$p = git push origin main 2>&1
Write-Host "  $p" -ForegroundColor Gray

Write-Host ""
Write-Host "TERMINE ! Retournez sur Vercel et cliquez Deploy." -ForegroundColor Green
Write-Host "URL finale : https://budgetnew.vercel.app" -ForegroundColor Cyan